#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# mission-control desktop labels
yabai -m space 1 --label ws1
yabai -m space 2 --label ws2
yabai -m space 3 --label ws3
yabai -m space 4 --label ws4
yabai -m space 5 --label ws5
yabai -m space 6 --label ws6
yabai -m space 7 --label ws7
yabai -m space 8 --label ws8
yabai -m space 9 --label ws9

# spacebarr is broken atm
#yabai -m config external_bar all:26:0

# window rules
yabai -m rule --add app="^Emacs$" space=ws1
yabai -m rule --add app="^zoom.us$" space=ws5
yabai -m rule --add app="^Google Chrome$" space=ws6
yabai -m rule --add app="^Microsoft Teams$" space=ws8
yabai -m rule --add app="^Microsoft Outlook$" space=ws8
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off

echo "yabai configuration loaded.."
