#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# mission-control desktop labels
yabai -m space 4 --label term
yabai -m space 5 --label emacs
yabai -m space 6 --label mongo
yabai -m space 7 --label postman
yabai -m space 8 --label scratch
yabai -m space 9 --label last
yabai -m space 1 --label web
yabai -m space 2 --label comms
yabai -m space 3 --label extra


# window rules
yabai -m rule --add app="^Emacs$" space=emacs
yabai -m rule --add app="^Zoom$" space=scratch
yabai -m rule --add app="^Chrome$" space=web
yabai -m rule --add app="^Teams$" space=comms
yabai -m rule --add app="^Outlook$" space=comms
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off

echo "yabai configuration loaded.."
